// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://majsgsecmbmwdcezehkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hanNnc2VjbWJtd2RjZXplaGtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwODUxMjYsImV4cCI6MjA2MDY2MTEyNn0.tdDuL5q1iyLQxBL2aSL-Dp_q0fjsl5AOqgpTvEC5fM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);